before_install:
- gem install mdl
- npm install -g markdown-link-check
script:
- mdl -c ./.mdlrc *.md
- markdown-link-check README.md
- markdown-link-check da_DK.md
- markdown-link-check de_DE.md
- markdown-link-check es_ES.md
- markdown-link-check fr_FR.md
- markdown-link-check it_IT.md
- markdown-link-check ja_JP.md
- markdown-link-check ko_KR.md
- markdown-link-check pt_BR.md
- markdown-link-check ru_RU.md
- markdown-link-check tr_TR.md
- markdown-link-check zh_CN.md
